name: quantum
description: A flutter plugin for dream project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.11.0"

flutter:
  plugin:
    platforms:
      android:
        package: xyz.huable.quantum
        pluginClass: QuantumPlugin
        ffiPlugin: true
      ios:
        pluginClass: QuantumPlugin
        ffiPlugin: true
      macos:
        pluginClass: QuantumPlugin
        ffiPlugin: true
      windows:
        pluginClass: QuantumPluginCApi
        ffiPlugin: true
      linux:
        pluginClass: QuantumPlugin
        ffiPlugin: true
      web:
        pluginClass: QuantumWeb
        fileName: quantum_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.3
  path_provider: ^2.1.5
  path: ^1.9.0
  logger: ^2.5.0
  crypto: ^3.0.6

dev_dependencies:
  ffigen: ^16.1.0
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter

#ffigen:
#  output: 'lib/generated_bindings.dart'
#  headers:
#    entry-points:
#      - 'src/quantum.h'