// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// ffi bindings for quantum plugin.
class QuantumNative {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  QuantumNative(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  QuantumNative.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int add(
    int a,
    int b,
  ) {
    return _add(
      a,
      b,
    );
  }

  late final _addPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('add');
  late final _add = _addPtr.asFunction<int Function(int, int)>();

  void QMLogInfo(
    ffi.Pointer<ffi.Char> message,
  ) {
    return _QMLogInfo(
      message,
    );
  }

  late final _QMLogInfoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'QMLogInfo');
  late final _QMLogInfo =
      _QMLogInfoPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<QKString> QKStringCreate(
    ffi.Pointer<ffi.Char> data,
  ) {
    return _QKStringCreate(
      data,
    );
  }

  late final _QKStringCreatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKString> Function(
              ffi.Pointer<ffi.Char>)>>('QKStringCreate');
  late final _QKStringCreate = _QKStringCreatePtr.asFunction<
      ffi.Pointer<QKString> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> QKStringGetData(
    ffi.Pointer<QKString> qkStr,
  ) {
    return _QKStringGetData(
      qkStr,
    );
  }

  late final _QKStringGetDataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<QKString>)>>('QKStringGetData');
  late final _QKStringGetData = _QKStringGetDataPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<QKString>)>();

  late final ffi.Pointer<ffi.Int> _QKSqliteValueNull =
      _lookup<ffi.Int>('QKSqliteValueNull');

  int get QKSqliteValueNull => _QKSqliteValueNull.value;

  late final ffi.Pointer<ffi.Int> _QKSqliteValueString =
      _lookup<ffi.Int>('QKSqliteValueString');

  int get QKSqliteValueString => _QKSqliteValueString.value;

  late final ffi.Pointer<ffi.Int> _QKSqliteValueInt =
      _lookup<ffi.Int>('QKSqliteValueInt');

  int get QKSqliteValueInt => _QKSqliteValueInt.value;

  late final ffi.Pointer<ffi.Int> _QKSqliteValueDouble =
      _lookup<ffi.Int>('QKSqliteValueDouble');

  int get QKSqliteValueDouble => _QKSqliteValueDouble.value;

  ffi.Pointer<QKString> QKSQliteColumnGetStringValue(
    ffi.Pointer<QKSqliteColumn> instance,
  ) {
    return _QKSQliteColumnGetStringValue(
      instance,
    );
  }

  late final _QKSQliteColumnGetStringValuePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKString> Function(
              ffi.Pointer<QKSqliteColumn>)>>('QKSQliteColumnGetStringValue');
  late final _QKSQliteColumnGetStringValue =
      _QKSQliteColumnGetStringValuePtr.asFunction<
          ffi.Pointer<QKString> Function(ffi.Pointer<QKSqliteColumn>)>();

  int QKSQliteColumnGetIntValue(
    ffi.Pointer<QKSqliteColumn> instance,
  ) {
    return _QKSQliteColumnGetIntValue(
      instance,
    );
  }

  late final _QKSQliteColumnGetIntValuePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<QKSqliteColumn>)>>(
      'QKSQliteColumnGetIntValue');
  late final _QKSQliteColumnGetIntValue = _QKSQliteColumnGetIntValuePtr
      .asFunction<int Function(ffi.Pointer<QKSqliteColumn>)>();

  int QKSQliteColumnGetDoubleValue(
    ffi.Pointer<QKSqliteColumn> instance,
  ) {
    return _QKSQliteColumnGetDoubleValue(
      instance,
    );
  }

  late final _QKSQliteColumnGetDoubleValuePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<QKSqliteColumn>)>>(
      'QKSQliteColumnGetDoubleValue');
  late final _QKSQliteColumnGetDoubleValue = _QKSQliteColumnGetDoubleValuePtr
      .asFunction<int Function(ffi.Pointer<QKSqliteColumn>)>();

  ffi.Pointer<QKString> QKSQliteColumnGetName(
    ffi.Pointer<QKSqliteColumn> instance,
  ) {
    return _QKSQliteColumnGetName(
      instance,
    );
  }

  late final _QKSQliteColumnGetNamePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKString> Function(
              ffi.Pointer<QKSqliteColumn>)>>('QKSQliteColumnGetName');
  late final _QKSQliteColumnGetName = _QKSQliteColumnGetNamePtr.asFunction<
      ffi.Pointer<QKString> Function(ffi.Pointer<QKSqliteColumn>)>();

  int QKSQliteColumnGetValueType(
    ffi.Pointer<QKSqliteColumn> instance,
  ) {
    return _QKSQliteColumnGetValueType(
      instance,
    );
  }

  late final _QKSQliteColumnGetValueTypePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<QKSqliteColumn>)>>(
      'QKSQliteColumnGetValueType');
  late final _QKSQliteColumnGetValueType = _QKSQliteColumnGetValueTypePtr
      .asFunction<int Function(ffi.Pointer<QKSqliteColumn>)>();

  int QKSqliteRowGetColumnCount(
    ffi.Pointer<QKSqliteRow> instance,
  ) {
    return _QKSqliteRowGetColumnCount(
      instance,
    );
  }

  late final _QKSqliteRowGetColumnCountPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<QKSqliteRow>)>>(
          'QKSqliteRowGetColumnCount');
  late final _QKSqliteRowGetColumnCount = _QKSqliteRowGetColumnCountPtr
      .asFunction<int Function(ffi.Pointer<QKSqliteRow>)>();

  ffi.Pointer<QKSqliteColumn> QKSqliteRowGetColumnByName(
    ffi.Pointer<QKSqliteRow> instance,
    ffi.Pointer<QKString> name,
  ) {
    return _QKSqliteRowGetColumnByName(
      instance,
      name,
    );
  }

  late final _QKSqliteRowGetColumnByNamePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKSqliteColumn> Function(ffi.Pointer<QKSqliteRow>,
              ffi.Pointer<QKString>)>>('QKSqliteRowGetColumnByName');
  late final _QKSqliteRowGetColumnByName =
      _QKSqliteRowGetColumnByNamePtr.asFunction<
          ffi.Pointer<QKSqliteColumn> Function(
              ffi.Pointer<QKSqliteRow>, ffi.Pointer<QKString>)>();

  ffi.Pointer<QKSqliteColumn> QKSqliteRowGetColumnByIndex(
    ffi.Pointer<QKSqliteRow> instance,
    int index,
  ) {
    return _QKSqliteRowGetColumnByIndex(
      instance,
      index,
    );
  }

  late final _QKSqliteRowGetColumnByIndexPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKSqliteColumn> Function(ffi.Pointer<QKSqliteRow>,
              ffi.Int)>>('QKSqliteRowGetColumnByIndex');
  late final _QKSqliteRowGetColumnByIndex =
      _QKSqliteRowGetColumnByIndexPtr.asFunction<
          ffi.Pointer<QKSqliteColumn> Function(
              ffi.Pointer<QKSqliteRow>, int)>();

  ffi.Pointer<QKSqliteRow> QKSqliteResultGetRow(
    ffi.Pointer<QKSqliteResult> instance,
    int index,
  ) {
    return _QKSqliteResultGetRow(
      instance,
      index,
    );
  }

  late final _QKSqliteResultGetRowPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKSqliteRow> Function(
              ffi.Pointer<QKSqliteResult>, ffi.Int)>>('QKSqliteResultGetRow');
  late final _QKSqliteResultGetRow = _QKSqliteResultGetRowPtr.asFunction<
      ffi.Pointer<QKSqliteRow> Function(ffi.Pointer<QKSqliteResult>, int)>();

  int QKSqliteResultGetRowCount(
    ffi.Pointer<QKSqliteResult> instance,
  ) {
    return _QKSqliteResultGetRowCount(
      instance,
    );
  }

  late final _QKSqliteResultGetRowCountPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<QKSqliteResult>)>>(
      'QKSqliteResultGetRowCount');
  late final _QKSqliteResultGetRowCount = _QKSqliteResultGetRowCountPtr
      .asFunction<int Function(ffi.Pointer<QKSqliteResult>)>();

  int QKSqliteCommandBindInt(
    ffi.Pointer<QKSqliteCommand> instance,
    ffi.Pointer<QKString> name,
    int value,
  ) {
    return _QKSqliteCommandBindInt(
      instance,
      name,
      value,
    );
  }

  late final _QKSqliteCommandBindIntPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<QKSqliteCommand>, ffi.Pointer<QKString>,
              ffi.Int)>>('QKSqliteCommandBindInt');
  late final _QKSqliteCommandBindInt = _QKSqliteCommandBindIntPtr.asFunction<
      int Function(ffi.Pointer<QKSqliteCommand>, ffi.Pointer<QKString>, int)>();

  int QKSqliteCommandBindString(
    ffi.Pointer<QKSqliteCommand> instance,
    ffi.Pointer<QKString> name,
    ffi.Pointer<QKString> value,
  ) {
    return _QKSqliteCommandBindString(
      instance,
      name,
      value,
    );
  }

  late final _QKSqliteCommandBindStringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<QKSqliteCommand>, ffi.Pointer<QKString>,
              ffi.Pointer<QKString>)>>('QKSqliteCommandBindString');
  late final _QKSqliteCommandBindString =
      _QKSqliteCommandBindStringPtr.asFunction<
          int Function(ffi.Pointer<QKSqliteCommand>, ffi.Pointer<QKString>,
              ffi.Pointer<QKString>)>();

  ffi.Pointer<QKSqliteResult> QKSqliteCommandRun(
    ffi.Pointer<QKSqliteCommand> instance,
  ) {
    return _QKSqliteCommandRun(
      instance,
    );
  }

  late final _QKSqliteCommandRunPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKSqliteResult> Function(
              ffi.Pointer<QKSqliteCommand>)>>('QKSqliteCommandRun');
  late final _QKSqliteCommandRun = _QKSqliteCommandRunPtr.asFunction<
      ffi.Pointer<QKSqliteResult> Function(ffi.Pointer<QKSqliteCommand>)>();

  int QKSqliteCommandClose(
    ffi.Pointer<QKSqliteCommand> instance,
  ) {
    return _QKSqliteCommandClose(
      instance,
    );
  }

  late final _QKSqliteCommandClosePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<QKSqliteCommand>)>>(
      'QKSqliteCommandClose');
  late final _QKSqliteCommandClose = _QKSqliteCommandClosePtr.asFunction<
      int Function(ffi.Pointer<QKSqliteCommand>)>();

  ffi.Pointer<QKSqliteService> QKSqliteServiceCreate(
    ffi.Pointer<QKString> message,
  ) {
    return _QKSqliteServiceCreate(
      message,
    );
  }

  late final _QKSqliteServiceCreatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKSqliteService> Function(
              ffi.Pointer<QKString>)>>('QKSqliteServiceCreate');
  late final _QKSqliteServiceCreate = _QKSqliteServiceCreatePtr.asFunction<
      ffi.Pointer<QKSqliteService> Function(ffi.Pointer<QKString>)>();

  void QKSqliteServiceDelete(
    ffi.Pointer<QKSqliteService> instance,
  ) {
    return _QKSqliteServiceDelete(
      instance,
    );
  }

  late final _QKSqliteServiceDeletePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<QKSqliteService>)>>(
      'QKSqliteServiceDelete');
  late final _QKSqliteServiceDelete = _QKSqliteServiceDeletePtr.asFunction<
      void Function(ffi.Pointer<QKSqliteService>)>();

  ffi.Pointer<QKSqliteCommand> QKSqliteServiceCreateCommand(
    ffi.Pointer<QKSqliteService> instance,
    ffi.Pointer<QKString> sqlText,
  ) {
    return _QKSqliteServiceCreateCommand(
      instance,
      sqlText,
    );
  }

  late final _QKSqliteServiceCreateCommandPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKSqliteCommand> Function(ffi.Pointer<QKSqliteService>,
              ffi.Pointer<QKString>)>>('QKSqliteServiceCreateCommand');
  late final _QKSqliteServiceCreateCommand =
      _QKSqliteServiceCreateCommandPtr.asFunction<
          ffi.Pointer<QKSqliteCommand> Function(
              ffi.Pointer<QKSqliteService>, ffi.Pointer<QKString>)>();

  ffi.Pointer<QKString> QKSqliteVersion(
    ffi.Pointer<QKSqliteService> instance,
  ) {
    return _QKSqliteVersion(
      instance,
    );
  }

  late final _QKSqliteVersionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKString> Function(
              ffi.Pointer<QKSqliteService>)>>('QKSqliteVersion');
  late final _QKSqliteVersion = _QKSqliteVersionPtr.asFunction<
      ffi.Pointer<QKString> Function(ffi.Pointer<QKSqliteService>)>();

  ffi.Pointer<QKSqliteResult> QKSqliteRunSql(
    ffi.Pointer<QKSqliteService> instance,
    ffi.Pointer<QKString> sqlText,
  ) {
    return _QKSqliteRunSql(
      instance,
      sqlText,
    );
  }

  late final _QKSqliteRunSqlPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<QKSqliteResult> Function(ffi.Pointer<QKSqliteService>,
              ffi.Pointer<QKString>)>>('QKSqliteRunSql');
  late final _QKSqliteRunSql = _QKSqliteRunSqlPtr.asFunction<
      ffi.Pointer<QKSqliteResult> Function(
          ffi.Pointer<QKSqliteService>, ffi.Pointer<QKString>)>();
}

final class QKString extends ffi.Struct {
  external ffi.Pointer<ffi.Void> mtStr;
}

final class QKSqliteColumn extends ffi.Struct {
  external ffi.Pointer<ffi.Void> mtSqliteColumn;
}

final class QKSqliteRow extends ffi.Struct {
  external ffi.Pointer<ffi.Void> mtSqlRow;
}

final class QKSqliteResult extends ffi.Struct {
  external ffi.Pointer<ffi.Void> mtSqlResult;
}

final class QKSqliteCommand extends ffi.Struct {
  external ffi.Pointer<ffi.Void> mtSqliteCommand;
}

final class QKSqliteService extends ffi.Struct {
  external ffi.Pointer<ffi.Void> mtSqlSvc;
}
