// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace quantum {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// DirectoryResponse

DirectoryResponse::DirectoryResponse() {}

DirectoryResponse::DirectoryResponse(
  const std::string* absolute_url,
  const std::string* bookmark_string)
 : absolute_url_(absolute_url ? std::optional<std::string>(*absolute_url) : std::nullopt),
    bookmark_string_(bookmark_string ? std::optional<std::string>(*bookmark_string) : std::nullopt) {}

const std::string* DirectoryResponse::absolute_url() const {
  return absolute_url_ ? &(*absolute_url_) : nullptr;
}

void DirectoryResponse::set_absolute_url(const std::string_view* value_arg) {
  absolute_url_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DirectoryResponse::set_absolute_url(std::string_view value_arg) {
  absolute_url_ = value_arg;
}


const std::string* DirectoryResponse::bookmark_string() const {
  return bookmark_string_ ? &(*bookmark_string_) : nullptr;
}

void DirectoryResponse::set_bookmark_string(const std::string_view* value_arg) {
  bookmark_string_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DirectoryResponse::set_bookmark_string(std::string_view value_arg) {
  bookmark_string_ = value_arg;
}


EncodableList DirectoryResponse::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(absolute_url_ ? EncodableValue(*absolute_url_) : EncodableValue());
  list.push_back(bookmark_string_ ? EncodableValue(*bookmark_string_) : EncodableValue());
  return list;
}

DirectoryResponse DirectoryResponse::FromEncodableList(const EncodableList& list) {
  DirectoryResponse decoded;
  auto& encodable_absolute_url = list[0];
  if (!encodable_absolute_url.IsNull()) {
    decoded.set_absolute_url(std::get<std::string>(encodable_absolute_url));
  }
  auto& encodable_bookmark_string = list[1];
  if (!encodable_bookmark_string.IsNull()) {
    decoded.set_bookmark_string(std::get<std::string>(encodable_bookmark_string));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        return CustomEncodableValue(DirectoryResponse::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(DirectoryResponse)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<DirectoryResponse>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by QuantumHostApi.
const flutter::StandardMessageCodec& QuantumHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `QuantumHostApi` to handle messages through the `binary_messenger`.
void QuantumHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  QuantumHostApi* api) {
  QuantumHostApi::SetUp(binary_messenger, api, "");
}

void QuantumHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  QuantumHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quantum.QuantumHostApi.getHostLanguage" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::string> output = api->GetHostLanguage();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quantum.QuantumHostApi.chooseDirectory" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::optional<DirectoryResponse>> output = api->ChooseDirectory();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quantum.QuantumHostApi.startAccessingSecurityScopedResource" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_bookmark_string_arg = args.at(0);
          if (encodable_bookmark_string_arg.IsNull()) {
            reply(WrapError("bookmark_string_arg unexpectedly null."));
            return;
          }
          const auto& bookmark_string_arg = std::get<std::string>(encodable_bookmark_string_arg);
          ErrorOr<std::optional<std::string>> output = api->StartAccessingSecurityScopedResource(bookmark_string_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(EncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quantum.QuantumHostApi.add" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_a_arg = args.at(0);
          if (encodable_a_arg.IsNull()) {
            reply(WrapError("a_arg unexpectedly null."));
            return;
          }
          const int64_t a_arg = encodable_a_arg.LongValue();
          const auto& encodable_b_arg = args.at(1);
          if (encodable_b_arg.IsNull()) {
            reply(WrapError("b_arg unexpectedly null."));
            return;
          }
          const int64_t b_arg = encodable_b_arg.LongValue();
          ErrorOr<int64_t> output = api->Add(a_arg, b_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quantum.QuantumHostApi.sendMessage" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_message_arg = args.at(0);
          if (encodable_message_arg.IsNull()) {
            reply(WrapError("message_arg unexpectedly null."));
            return;
          }
          const auto& message_arg = std::get<std::string>(encodable_message_arg);
          api->SendMessage(message_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue QuantumHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue QuantumHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace quantum
