// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace quantum {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class QuantumHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class MessageData {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MessageData(const flutter::EncodableMap& data);

  // Constructs an object setting all fields.
  explicit MessageData(
    const std::string* name,
    const std::string* description,
    const flutter::EncodableMap& data);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  const std::string* description() const;
  void set_description(const std::string_view* value_arg);
  void set_description(std::string_view value_arg);

  const flutter::EncodableMap& data() const;
  void set_data(const flutter::EncodableMap& value_arg);


 private:
  static MessageData FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class QuantumHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> name_;
  std::optional<std::string> description_;
  flutter::EncodableMap data_;

};


// Generated class from Pigeon that represents data sent in messages.
class DirectoryResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  DirectoryResponse();

  // Constructs an object setting all fields.
  explicit DirectoryResponse(
    const std::string* absolute_url,
    const std::string* bookmark_string);

  const std::string* absolute_url() const;
  void set_absolute_url(const std::string_view* value_arg);
  void set_absolute_url(std::string_view value_arg);

  const std::string* bookmark_string() const;
  void set_bookmark_string(const std::string_view* value_arg);
  void set_bookmark_string(std::string_view value_arg);


 private:
  static DirectoryResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class QuantumHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> absolute_url_;
  std::optional<std::string> bookmark_string_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class QuantumHostApi {
 public:
  QuantumHostApi(const QuantumHostApi&) = delete;
  QuantumHostApi& operator=(const QuantumHostApi&) = delete;
  virtual ~QuantumHostApi() {}
  virtual ErrorOr<std::string> GetHostLanguage() = 0;
  virtual ErrorOr<std::optional<DirectoryResponse>> ChooseDirectory() = 0;
  virtual ErrorOr<std::optional<std::string>> StartAccessingSecurityScopedResource(const std::string& bookmark_string) = 0;
  virtual ErrorOr<int64_t> Add(
    int64_t a,
    int64_t b) = 0;
  virtual void SendMessage(
    const MessageData& message,
    std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by QuantumHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `QuantumHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    QuantumHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    QuantumHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  QuantumHostApi() = default;

};
}  // namespace quantum
#endif  // PIGEON_MESSAGES_G_H_
